Fix init files
Systemctl doesn't set `UID` leading to syntax error in the `UID` check.
Easiest fix is to disable the check.

diff --git a/ansible/roles/delia/files/delia.init b/ansible/roles/delia/files/delia.init
--- a/ansible/roles/delia/files/delia.init
+++ b/ansible/roles/delia/files/delia.init
@@ -44,10 +44,10 @@ if ! [ -x $DAEMON ];then
   exit 1 
 fi
 
-if [ $UID -gt 0 ]; then
-  echo "ERROR - must run as root"
-  exit 1
-fi
+# if [ $UID -gt 0 ]; then
+#   echo "ERROR - must run as root"
+#   exit 1
+# fi
 
 # # XXX - hack to ensure GPGME works
 # if [ "$HOME" != "/root" ]; then
diff --git a/ansible/roles/emma/files/emma.init b/ansible/roles/emma/files/emma.init
--- a/ansible/roles/emma/files/emma.init
+++ b/ansible/roles/emma/files/emma.init
@@ -46,10 +46,10 @@ if ! [ -x $DAEMON ];then
   exit 1 
 fi
 
-if [ $UID -gt 0 ]; then
-  echo "ERROR - must run as root"
-  exit 1
-fi
+# if [ $UID -gt 0 ]; then
+#   echo "ERROR - must run as root"
+#   exit 1
+# fi
 
 if [ -z "$2" ]; then
   DAEMON_OPTS=""
diff --git a/ansible/roles/package-daemons/files/ct-capacity-daemon.init b/ansible/roles/package-daemons/files/ct-capacity-daemon.init
--- a/ansible/roles/package-daemons/files/ct-capacity-daemon.init
+++ b/ansible/roles/package-daemons/files/ct-capacity-daemon.init
@@ -30,7 +30,7 @@
 # Default-Stop:      0 1 6
 ### END INIT INFO
 
-PATH=/sbin:/bin:/usr/sbin:/usr/bin
+PATH=/opt/ruby-1.9/bin:/sbin:/bin:/usr/sbin:/usr/bin
 NAME=ct-capacity-daemon
 DESC="ct-capacity-daemon"
 DIR=/data/private/share/daemons/ct-capacity-daemon
@@ -45,10 +45,10 @@ if ! [ -x $DAEMON ];then
   exit 1 
 fi
 
-if [ $UID -gt 0 ]; then
-  echo "ERROR - must run as root"
-  exit 1
-fi
+# if [ $UID -gt 0 ]; then
+#   echo "ERROR - must run as root"
+#   exit 1
+# fi
 
 cd $DIR
 
diff --git a/ansible/roles/package-daemons/files/enid.init b/ansible/roles/package-daemons/files/enid.init
--- a/ansible/roles/package-daemons/files/enid.init
+++ b/ansible/roles/package-daemons/files/enid.init
@@ -31,7 +31,7 @@
 # Default-Stop:      0 1 6
 ### END INIT INFO
 
-PATH=/sbin:/bin:/usr/sbin:/usr/bin
+PATH=/opt/ruby-1.9/bin:/sbin:/bin:/usr/sbin:/usr/bin
 NAME=enid
 DESC="Phoenix ENID"
 DIR=/data/private/share/daemons/enid
@@ -46,10 +46,10 @@ if ! [ -x $DAEMON ];then
   exit 1 
 fi
 
-if [ $UID -gt 0 ]; then
-  echo "ERROR - must run as root"
-  exit 1
-fi
+# if [ $UID -gt 0 ]; then
+#   echo "ERROR - must run as root"
+#   exit 1
+# fi
 
 cd $DIR
 
diff --git a/ansible/roles/package-daemons/files/martha.init b/ansible/roles/package-daemons/files/martha.init
--- a/ansible/roles/package-daemons/files/martha.init
+++ b/ansible/roles/package-daemons/files/martha.init
@@ -29,7 +29,7 @@
 # Default-Stop:      0 1 6
 ### END INIT INFO
 
-PATH=/sbin:/bin:/usr/sbin:/usr/bin
+PATH=/opt/ruby-1.9/bin:/sbin:/bin:/usr/sbin:/usr/bin
 NAME=martha
 DESC="Phoenix MARTHA"
 DIR=/data/private/share/daemons/martha
@@ -46,10 +46,10 @@ if ! [ -x $DAEMON ];then
   exit 1 
 fi
 
-if [ $UID -gt 0 ]; then
-  echo "ERROR - must run as root"
-  exit 1
-fi
+# if [ $UID -gt 0 ]; then
+#   echo "ERROR - must run as root"
+#   exit 1
+# fi
 
 cd $DIR
 
